name: 🔄 TC 마스터 복제 및 상위 이슈 연결 (이슈 생성 자동화)

on:
  workflow_dispatch:
    inputs:
      parent_issue_id: # ✅ 수정됨: 콜론만 남기고 아래 속성 정의
        description: '복제된 TC들이 연결될 Target Repo의 상위(Parent) 이슈 번호 (예: 212)'
        required: true
        default: '212'
      source_repo: # ✅ 수정됨: 콜론만 남김
        description: '마스터 TC가 있는 Source Repo 전체 경로 (예: Automata-LG/TC-Master_LGE-APP)'
        required: true
        default: 'Automata-LG/TC-Master_LGE-APP' 
      target_project_url: # ✅ 수정됨: 콜론만 남김
        description: '복제된 이슈를 추가할 LG_SM Project Board의 URL'
        required: true
        default: 'https://github.com/orgs/Automata-LG/projects/1/views/1'

jobs:
  clone_and_nest:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read 

    steps:
    - name: 코드 체크아웃 (필수 단계)
      uses: actions/checkout@v4
      
    - name: GitHub CLI 및 환경 변수 설정
      env:
        GH_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}
        SOURCE_REPO: ${{ github.event.inputs.source_repo }}
        TARGET_REPO: ${{ github.repository }}
        
      run: |
        echo "Source Repo: $SOURCE_REPO"
        echo "Target Repo (복제 대상): $TARGET_REPO"
        
    - name: 이슈 복제, 하위 이슈 연결 및 프로젝트 추가 로직 실행
      env:
        PARENT_ISSUE_ID: ${{ github.event.inputs.parent_issue_id }}
        PROJECT_URL: ${{ github.event.inputs.target_project_url }}
        
      run: |
        echo "--- 4. 마스터 TC 목록 조회 (Source Repo에서) ---"
        # $SOURCE_REPO 변수를 큰따옴표로 감싸서 Shell이 하나의 인수로 처리하도록 보장합니다.
        MASTER_ISSUES=$(gh issue list \
          --repo "$SOURCE_REPO" \  # ✅ 수정됨: 따옴표 추가
          --label "TC-Master" \
          --state open \
          --json title,body \
          --jq '.[] | @base64')

        if [ -z "$MASTER_ISSUES" ]; then
          echo "조회된 마스터 TC 이슈가 없습니다. 워크플로우를 종료합니다."
          exit 0
        fi
        
        echo "--- 5. 복제, 하위 이슈 연결 및 프로젝트 추가 시작 ---"
        
        echo "$MASTER_ISSUES" | while read -r ISSUE_DATA; do
          
          _jq() {
            echo "$ISSUE_DATA" | base64 --decode | jq -r "${1}"
          }
          TITLE=$(_jq '.title')
          BODY=$(_jq '.body')
          
          NEW_TITLE="${TITLE}"
          NEW_BODY="## [마스터 TC 복제]\n\n**상위(Parent) 이슈:** #${PARENT_ISSUE_ID}\n\n---\n\n${BODY}"
          
          # 6. 라벨 설정
          NEW_LABELS="QA, App" # ✅ 수정됨: 닫는 따옴표 추가
          
          # 7. 새로운 이슈를 Target Repo(backlog-lg)에 생성 (이슈 복제)
          echo "   -> 복제 중: $NEW_TITLE"
          NEW_ISSUE_NUMBER=$(gh issue create \
            --repo $TARGET_REPO \
            --title "$NEW_TITLE" \
            --body "$NEW_BODY" \
            --label "$NEW_LABELS" \
            --json number --jq .number)
            
          echo "   ✅ 새 이슈 생성 완료: #${NEW_ISSUE_NUMBER}"

          # 8. 새로 생성된 이슈를 Project Board에 추가
          gh project item add $NEW_ISSUE_NUMBER \
            --repo $TARGET_REPO \
            --url "$PROJECT_URL"

          # 9. Parent Issue와의 연결 (Relates to)
          gh issue link $NEW_ISSUE_NUMBER $PARENT_ISSUE_ID \
            --repo $TARGET_REPO \
            --add "relates to" 

          echo "   ✅ Parent #$PARENT_ISSUE_ID 연결 및 Project 추가 완료"
          
        done

        echo "--- 10. 모든 복제 및 연결 작업 완료 ---"
